---
name: Release the Ansible Collection
on:
  workflow_call:
    inputs:
      ah_publish:
        description: Publish the collection on automation hub
        default: true
        type: boolean
      environment:
        description: The deployment environment
        required: true
        type: string
      galaxy_publish:
        default: true
        description: Publish the collection on galaxy
        type: boolean
    secrets:
      ah_token:
        required: false
      ansible_galaxy_api_key:
        required: false

jobs:
  release_automation_hub:
    uses: KB-perByte/hold_gha/.github/workflows/release_ah.yml@main
    with:
      environment: release
    secrets:
      ah_token: ${{ secrets.AH_TOKEN }}

  release_galaxy:
    uses: KB-perByte/hold_gha/.github/workflows/release_galaxy.yml@main
    needs: [release_automation_hub]
    with:
      environment: release
    secrets:
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
