---
name: Check changelog
"on":
  workflow_call: null
jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Requires changelog
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-changelog')"
    steps:
      - name: Checkout the collection repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          fetch-depth: "0"
      - name: Validate changelog
        uses: >-
          ./github/actions/ansible_validate_changelog
