---
name: Check label
"on":
  workflow_call:
    secrets:
      BOT_PAT:
        required: false
jobs:
  check_label:
    runs-on: ubuntu-latest
    environment: push
    permissions:
      checks: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@v6
        if: "${{ github.event_name == 'pull_request' }}"
        with:
          disable-autolabeler: false
          disable-releaser: true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        continue-on-error: true
      - name: Verify PR label action
        if: "${{ github.event_name == 'pull_request' }}"
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: >-
            bug, enhancement, feature, refactoring, major, deprecated,
            skip-changelog, bot:chronographer:skip
          invalid-labels: "help wanted, invalid, feedback-needed, incomplete"
          pull-request-number: "${{ github.event.pull_request.number }}"
          disable-reviews: true
      - name: Update release notes if this is already merged
        if: github.event.pull_request.merged == true
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Add issue or pull-request to 'devtools' project
        env:
          BOT_PAT: "${{ secrets.BOT_PAT }}"
        if: env.BOT_PAT != null
        uses: actions/add-to-project@main
        with:
          project-url: "https://github.com/orgs/ansible/projects/86"
          github-token: "${{ secrets.BOT_PAT }}"
