name: CML Lab Destroy

on:
  workflow_call:
    inputs:
      lab_title_override:
        description: Optional lab title override; if empty uses PR title
        required: false
        type: string
        default: ""
    secrets:
      virl_host:
        required: true
      virl_username:
        required: false
      virl_password:
        required: true

jobs:
  destroy_lab:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: "1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine lab title
        id: lab
        shell: bash
        run: |
          set -euo pipefail
          title="${{ inputs.lab_title_override }}"
          if [[ -z "$title" && "{{ github.event_name }}" == "pull_request" ]]; then
            title="${{ github.event.pull_request.title }}"
          fi
          if [[ -z "$title" ]]; then
            title="${{ github.repository }}-${{ github.run_id }}"
          fi
          clean_title=$(sed -E 's/[^A-Za-z0-9 _-]+//g; s/[[:space:]]+/ /g; s/^ +| +$//g' <<<"$title")
          echo "title=$clean_title" >> "$GITHUB_OUTPUT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ansible and CML collection
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible-core==2.18
          python -m pip install virl2_client==2.7.1
          ansible-galaxy collection install git+https://github.com/KB-perByte/cml.git

      - name: Create destroy playbook
        shell: bash
        run: |
          cat > cml_destroy.yml <<'YAML'
          ---
          - hosts: localhost
            gather_facts: no
            connection: local
            tasks:
              - name: Stop the lab
                cisco.cml.cml_lab:
                  host: "{{ cml_host }}"
                  user: "admin"
                  password: "{{ cml_password }}"
                  lab: "{{ cml_lab }}"
                  state: stopped
                tags:
                  - stop
                  - wipe
                  - erase
              - name: Wipe the lab
                cisco.cml.cml_lab:
                  host: "{{ cml_host }}"
                  user: "admin"
                  password: "{{ cml_password }}"
                  lab: "{{ cml_lab }}"
                  state: wiped
                tags:
                  - wipe
                  - erase
              - name: Erase the lab
                cisco.cml.cml_lab:
                  host: "{{ cml_host }}"
                  user: "admin"
                  password: "{{ cml_password }}"
                  lab: "{{ cml_lab }}"
                  state: absent
                tags:
                  - erase
          YAML

      - name: Run destroy playbook
        shell: bash
        env:
          CML_HOST: ${{ secrets.virl_host }}
          CML_USERNAME: ${{ secrets.virl_username || 'admin' }}
          CML_PASSWORD: ${{ secrets.virl_password }}
          CML_LAB: ${{ steps.lab.outputs.title }}
          CML_VERIFY_CERT: "false"
        run: |
          set -euo pipefail
          echo "Destroying lab: $CML_LAB"
          ansible-playbook cml_destroy.yml \
            -e cml_host="$CML_HOST" \
            -e cml_username="$CML_USERNAME" \
            -e cml_password="$CML_PASSWORD" \
            -e cml_lab="$CML_LAB"
