---
# See https://github.com/ansible/team-devtools/blob/main/.github/workflows/push.yml
name: push
"on":
  push:
    branches:
      - main
      - "releases/**"
      - "stable/**"

jobs:
  ack:
    uses: ansible/team-devtools/.github/workflows/push.yml@0f4f5b158f9e60ecedec0fd7825892246c8664a2 # main
