---
name: Automation hub release
'on':
  workflow_call:
    inputs:
      ah_publish:
        description: Publish the collection on automation hub
        default: true
        type: boolean
      environment:
        description: The deployment environment
        required: true
        type: string
    secrets:
      ah_token:
        required: false
      ah_client_id:
        required: false
      ah_client_secret:
        required: false
jobs:
  release:
    runs-on: ubuntu-latest
    name: Automation Hub release
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ansible
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "ansible-core>=2.15"

      - name: Build the collection
        run: |
          ansible-galaxy collection build -v --force

      - name: Publish with ah_token
        if: ${{ inputs.ah_publish }}
        env:
          AH_TOKEN: ${{ secrets.ah_token }}
        run: |
          if [[ -z "$AH_TOKEN" ]]; then
            echo "Skipping: ah_token not provided"
            exit 0
          fi
          TARBALL=$(ls -1 ./*.tar.gz | head -n1)
          cat > ansible.cfg <<EOF
          [galaxy]
          server_list = rh_automation_hub

          [galaxy_server.rh_automation_hub]
          url=https://cloud.redhat.com/api/automation-hub/
          auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          token=$AH_TOKEN
          EOF

          ansible-galaxy collection publish "${TARBALL}"
          rm -f ansible.cfg

      - name: Publish with ah_client_id and ah_client_secret
        if: ${{ inputs.ah_publish }}
        env:
          AH_CLIENT_ID: ${{ secrets.ah_client_id }}
          AH_CLIENT_SECRET: ${{ secrets.ah_client_secret }}
        run: |
          if [[ -z "$AH_CLIENT_ID" || -z "$AH_CLIENT_SECRET" ]]; then
            echo "Skipping: ah_client_id or ah_client_secret not provided"
            exit 0
          fi
          TARBALL=$(ls -1 ./*.tar.gz | head -n1)
          cat > ansible.cfg <<EOF
          [galaxy]
          server_list = automation_hub

          [galaxy_server.automation_hub]
          url=https://cloud.redhat.com/api/automation-hub/
          auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          client_id=$AH_CLIENT_ID
          client_secret=$AH_CLIENT_SECRET
          EOF

          ansible-galaxy collection publish "${TARBALL}"
          rm -f ansible.cfg

      - name: Fail if no Automation Hub credentials
        if: ${{ inputs.ah_publish }}
        env:
          AH_TOKEN: ${{ secrets.ah_token }}
          AH_CLIENT_ID: ${{ secrets.ah_client_id }}
          AH_CLIENT_SECRET: ${{ secrets.ah_client_secret }}
        run: |
          if [[ -n "$AH_TOKEN" ]] || [[ -n "$AH_CLIENT_ID" && -n "$AH_CLIENT_SECRET" ]]; then
            echo "Valid credentials found, skipping failure step"
            exit 0
          fi
          echo "Error: No valid Automation Hub credentials provided." 1>&2
          echo "Provide 'ah_token' OR both 'ah_client_id' and 'ah_client_secret'." 1>&2
          exit 1
